name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Lua 5.1
      uses: docker://mileschou/lua:5.1
      with:
        args: lua test/test.lua

    - name: Lua 5.2
      uses: docker://mileschou/lua:5.2
      with:
        args: lua test/test.lua

    - name: Lua 5.3
      uses: docker://mileschou/lua:5.3
      with:
        args: lua test/test.lua

    - name: LuaJIT
      uses: docker://mileschou/lua:jit-2.1
      with:
        args: luajit test/test.lua
